[package]
name = "refactor-js-project"
version = "0.1.0"
authors = ["woorui <rui1009479218@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

structopt = "0.3.13"
glob = "0.3.0"